export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_ENTRIES_ERROR = 'FETCH_ENTRIES_ERROR';
export const FETCH_ENTRY_SUCCESS = 'FETCH_ENTRY_SUCCESS';
export const FETCH_ENTRY_ERROR = 'FETCH_ENTRY_ERROR';
export const CHANGE_VIEW_MODE = 'CHANGE_VIEW_MODE';